### PR TITLE
#212 Invoices.contributorVat DB Column

### LINKED ISSUE #212: Implement Invoice.contributorVat
We need this DB column and we also need to update the ``registerAsPaid(...)`` method to set its value.

### PR DESCRIPTION
**Pull request by amihaiemil**
Fixes #212 

* Created Invoices.contributorVat DB Column;
* Updated to self-core 0.0.49-SNAPSHOT;
* Updated method registerAsPaid(...) to also set the contributorVat
* tests

We are waiting now for the release of core 49, then we will merge this.

### CODE REVIEW

**Comment by charlesmike** [comment]
@amihaiemil thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-01-09T11:38:50.304058``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

**Comment by amihaiemil** [comment]
will go with another design, we have to save Self's invoices to Contributors in a different table.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Pull request closed without merging**
