### PR TITLE
#121. Fixed `slf_tasks_xdsd` fk reference of `slf_contracts_xdsd`.

### PR DESCRIPTION
**Pull request by criske**
Fixes for #121

### CODE REVIEW

**Comment by amihaiemil** [comment]
@rultor merge it

**Comment by amihaiemil** [comment]
@criske I think you also have to modify some insert statements:

```sql
Failed to execute:  
 INSERT INTO self_xdsd.slf_tasks_xdsd
 (repo_fullname, issueId, provider, role, username, assigned, deadline, estimation_minutes)
 VALUES
 ('amihaiemil/docker-java-api', '123', 'github', 'DEV', 'alexandra', '2020-06-07', '2020-06-17', 60)
```

**Comment by criske** [comment]
@amihaiemil Sorry about that.
FOREIGN KEY needed to have the fields in the same order too. Inserts are fine.
It should work now.

**Comment by amihaiemil** [comment]
@rultor merge it

**Pull request merged**
